#0. Prerequirements
sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install: 
#   - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d # Encripted service-account.json file 
# #1. Install google cloud SDK CLI
#   - curl https://sdk.cloud.google.com | bash > /dev/null;

# #2. Configure the SDK with out Google cloud auth info
#   - source $HOME/google-cloud-sdk/path.bash.inc
#   - gcloud components update kubectl
#   - gcloud auth activate-service-account --key-file service-account.json
#   - gcloud config set project multi-k8s-315309 # project id in google cloud
#   - gcloud config set compute/zone us-central1-a # Project zone
#   - gcloud container clusters get-credentials multi-cluster #cluster name

#3. Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#4. Build the test version of the multi-client
  - docker build -t dominic70/react-test -f ./client/Dockerfile.dev ./client

#5. Run test
script:
  - docker run dominic70/react-test npm test -- --coverage

#6. If test run successful, run a script to deploy newest images
# after_success:

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
