#0. Prerequirements
sudo: required
services:
  - docker
before_install: 
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d # Encripted service-account.json file 
#1. Install google cloud SDK CLI
  - curl https://sdk.cloud.google.com | bash > /dev/null;

#2. Configure the SDK with out Google cloud auth info
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json

#3. Login to Docker CLI

#4. Build the test version of the multi-client

#5. Run test

#6. If test run successful, run a script to deply newest images

#7. Build our images, tag each one, push each to docker hub

#8. Apply all configs in the k8s folder

#9. Imperactively set latest image on each deployment 