apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingess-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod' #for prod
    nginx.ingress.kubernetes.io/ssl-redirect: 'true' #for prod
spec:
  tls: #for prod
    - hosts: #for prod
        - "k8s-multi.com" #for prod
        - "www.k8s-multi.com" #for prod
      secretName: k8s-multi-com #for prod
  rules:
    - host: k8s-multi-com #for prod
      http:
        paths:
        - path: "/"
          backend:
            serviceName: client-cluster-ip-service
            servicePort: 3000
        - path: "/api/"
          backend:
            serviceName: server-cluster-ip-service
            servicePort: 5000
    - host: www.k8s-multi.com #for prod <- we have to repeat for www host 
      http:
        paths:
        - path: "/"
          backend:
            serviceName: client-cluster-ip-service
            servicePort: 3000
        - path: "/api/"
          backend:
            serviceName: server-cluster-ip-service
            servicePort: 5000
